name: Build Alpine Package

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fix git safe directory
      run: git config --global --add safe.directory /github/workspace

    - name: Setup Alpine build environment
      run: |
        sudo apt update
        sudo apt install -y alpine-sdk
        mkdir -p ~/.abuild
        abuild-keygen -a -n

    - name: Build package
      run: |
        abuild -r

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: alpine-apk-package
        path: ~/packages/**/*.apk
